setwd("~/Dropbox/Code/Starfighter/sfobjects")
devtools::setup(".", rstudio=FALSE)
devtools::use_testthat()
devtools::document()
devtools::use_package("methods")
devtools::use_package("stockfighterr")
devtools::use_package("httr")
devtools::use_package("jsonlite")
devtools::use_package("magrittr", type="Depends")
devtools::use_package("purrr")
devtools::use_package("future")
devtools::use_package("withr")
devtools::check(".")
devtools::build(".")
devtools::test(".")
devtools::install(".")
